# Generated by Django 4.2.23 on 2026-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('rain', models.FloatField()),
                ('water_level_krl', models.FloatField()),
                ('water_level_kai', models.FloatField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
