# Generated by Django 4.2.23 on 2026-05-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain_value', models.FloatField()),
                ('krl_water_level', models.FloatField()),
                ('kai_water_level', models.FloatField()),
                ('status', models.CharField(choices=[('AMAN', 'AMAN'), ('KRL STOP', 'KRL STOP'), ('TOTAL STOP', 'TOTAL STOP')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
